:toc:
:toc-placement!:
:toc-title: Sommaire

= SAE 1.06 - Découverte d'un environnement économique et écologique
_Réalisé par HURÉ Tilian et FERNANDEZ Mickael (4A)_

toc::[]

== Page d'accueil

=== Présentation du site

Bienvenue sur le site web comparatif des entreprises GreenTech choisies par Tilian .H et Mickaël .F.

Retrouvez sur le site, la présentation des deux entreprises GreenTech choisies dans le contexte de la SAE 1.06 se déroulant à l’IUT de Blagnac, ainsi que le comparatif de leur stratégie respective. (https://tilian-hure.github.io/SAE1.06/pages/index.html)

=== Présentation GreenTech

La Greentech rassemble des organisations cherchant à innover dans les nouvelles technologies durables, dans le respect et la protection de l’environnement. Ainsi, elle contribue écologiquement au développement durable avec pour objectif principal de réduire l’empreinte carbone sur Terre.

Les organisations GreenTech se retrouvent dans plusieurs domaines, comme les énergies renouvelables, l’agriculture, les transports propres, mais aussi la santé ou encore le numérique durable.

== ILEK

Dans ce document, vous retrouverez l'analyse complète de la société ILEK. Pour en savoir plus sur Adagos, consultez notre site : https://tilian-hure.github.io/SAE1.06/pages/index.html

=== Tableau récapitulatif

|===
|Entreprise |ILEK
|Secteur d'activité |Fournisseur local spécialisé dans le gaz bio et renouvelable en résidentiel ainsi que dans l’électricité verte pour les particuliers et les petites entreprises.
|Date de création et fondateurs |Création en septembre 2015 par Julien CHARDON et Rémy COMPANYO. (Date d’officialisation le 6 mai 2016)
|Lieu |Toulouse (France)
|PDG |Rémy COMPANYO - Cofondateur et CMO d’Ilek +
Julien CHARDON - Cofondateur, CEO et directeur d’Ilek.
|Taille | Environ 100 salariés - PME
|Domaine GreenTech | Énergies renouvelables
|===

==== Dates clés et évolutions :

- *2016* : Acquisition de l’agrément de fourniture d’énergie verte auprès de ses fournisseurs et apparition de premières offres d’énergie verte française proposées auprès de sa clientèle;
- *2018* : Diversification de l’approvisionnement d’énergies renouvelables : lancement sur le marché du biométhane;
- *2020* : Ilek s’insère dans le programme French Tech 120 et devient le premier fournisseur d’énergie renouvelable français à obtenir le label B Corp (certification rare accordée à des sociétés commerciales satisfaisant les critères environnementaux).

=== Histoire

À Toulouse dans un incubateur d’entreprises, les cofondateurs d’Ilek, Julien CHARDON et Rémy COMPANYO se rencontrent. Tous les deux, transportés par l'entreprenariat, admettent un bilan sur lequel ces deux-ci pourraient agir en conséquence : le manque d’équilibre sur le marché de l’énergie. Puisque en effet, leur objectif serait de rendre l’énergie renouvelable accessible à tous et en toute transparence. Grâce à leur qualification et pour conclure leurs idées, ils décident de fonder en 2015 Ilek, une plateforme qui permettra de mettre en lien direct les producteurs avec les consommateurs de manière réactive et durable.

La même année, l’entreprise réalise un juste chiffre d’affaires de 5 200€. Puis en 2019, elle effectue une levée de fonds de 6 millions d’euros auprès des investisseurs Alter Equity, Kima Ventures et Sorepar afin d’être plus éligible à collaborer avec d’autres entreprises du domaine.

L’organisation s’est vu se développer à une vitesse remarquable, atteignant un chiffre d’affaires avoisinant les 55 millions d’euros actuellement.

=== Modèles économiques

Le modèle économique correspond à la manière qu’utilise l’entreprise pour générer de la rentabilité, notamment caractérisée par une croissance et une internationalisation de celle-ci.

==== L'achat-revente :

Contrairement aux fournisseurs historiques du pays, Ilek se procure de l’énergie verte auprès de 40 producteurs partenaires en France rémunérés au juste prix, ainsi que leur garantie d’origine afin de revendre cette énergie à une clientèle ambitieuse de changement, pour un tarif plus compétitif que la concurrence.

La différence se réalise donc de cette création de valeur entre le prix acheté et le prix vendu.

==== Le B2C (Business to Consumer) :

La petite société utilise également la stratégie du “B2C” ou “Business to Consumer”, ciblant des clients particuliers étant les consommateurs finaux de l’entreprise. Ilek réalise donc son activité en ligne et vend ainsi des produits directement à des particuliers, d’où sa politique de “customer first” traduite, notamment dans la composition de l’équipe, à 55% au service client et 20% sur le marketing et la communication ; le reste étant dédié au développement du site et à l’énergie.

=== Chaînes de valeur

La chaîne de valeur d’une entreprise correspond à l’ensemble des activités au sein d’une société qui génèrent ou qui, au contraire, détruisent de la valeur.

==== Activités principales :

===== L'approvisionnement :

- L’entreprise garantit et réalise son approvisionnement en énergie verte/renouvelable autour de producteurs locaux, pour des clients désireux de changement ainsi que toute la facturation.

===== La fabrication / production :

- La fabrication de ces produits n’est pas réalisée par Ilek car c’est dans le rôle des producteurs locaux d’électricité verte et de gaz vert;
- Pour réaliser ces productions d’énergie et respecter les normes, les producteurs utilisent des parcs éoliens, des champs de panneaux solaires, des centrales hydroélectriques ou encore des fermes de biogaz. 

===== La commercialisation :

- Les installations des producteurs ne comprennent aucun stockage d’énergie mais elles re-distribuent en revanche le surplus sur le réseau public.

===== La vente et le marketing :

- Ilek propose à ses clients de parrainer leurs proches et connaissances pour gagner des kWh qui peuvent être utilisés pour les déduire de leurs factures par exemple. Il s’agit d’un gain de 100 kWh pour le parrain et le filleul à chaque personne parrainée;
- Le fournisseur met en avant sur les réseaux sociaux les producteurs d’énergie renouvelable afin de les rendre plus accessibles pour ses clients et d’attirer une plus grande part de nouveaux clients.

===== Les services / offres :

- Ilek est gratuit et sans frais d’entrée lorsqu’un client s’engage dans l’entreprise. Par ailleurs, les contrats sont également sans engagement;
- Pour conserver des prix concurrentiels, l’organisation a choisi d’investir dans la technologie et de travailler avec des entreprises ayant une approche équivalente.

==== Activités de soutien :

===== Les infrastructures :

- Les clients peuvent contacter le SAV d’ilek pour des informations relatives sur le compte, le contrat, le compteur ou encore faire une réclamation et bien d’autres encore.

===== Les ressources humaines :

Pour assurer la gestion du personnel et de sa coordination, Ilek possède à ce compte :

- Des content & community manager (contenu & communauté);
- Des social media manager (réseaux sociaux);
- Des digital acquisition manager (acquisition numérique);
- Des customer care manager (service clientèle);
- Des account manager (gestionnaire);
- Des product manager back office (produit back office).

===== La recherche et le développement :

- Dans Ilek, la recherche de producteurs se réalise par des business developers. La recherche de nouveaux produits est en revanche difficile pour l’équipe. Prochainement, la petite entreprise devrait trouver des producteurs d’énergie verte utilisant des centrales géothermiques;
- Enfin, pour des personnes possédant des capacités d’innovation, Ilek propose et possède des développeurs frontend et backend ainsi que des software engineer (ingénieur logiciel).

===== Les achats :

- Ilek achète de l’énergie verte ainsi que leur garantie auprès de producteurs partenaires en France dans le but de la revendre.

=== Environnement concurrentiel

Ilek dispose de forces ainsi que de faiblesses comme la plupart des entreprises concurrentes. Malgré les avantages ou les offres que propose l’entreprise, elle n’est pourtant pas la seule et unique entreprise à se situer dans le domaine et à proposer des produits ressemblants.

==== Forces :

Ilek est le seul fournisseur local d’électricité verte à proposer cette mise en rapport avec des fabricants d’énergies renouvelables. Le futur consommateur peut alors choisir le producteur français de son choix ainsi que son énergie 100% propre qu’il souhaite adopter sans coût additionnel. L’entreprise réalise une réduction de 25% de la production de CO2.

Pour des renseignements quelconques, le client bénéficie à la fois d’un suivi de sa consommation en ligne ainsi que d’un service client téléphonique français.

==== Faiblesses :

La société toulousaine commence à se faire une renommée mais elle reste une entreprise assez mineure malgré son soutien actif pour la transition écologique. Ilek reste relativement assez éloigné de son objectif notamment dû à une forte concurrence et à une indépendance du pays sur le secteur nucléaire.

Enfin, l’offre combinée électricité plus gaz d’Ilek possède un tarif relativement élevé et donc pas adapté à tous les budgets malgré son annonce de prix concurrents.

==== Concurrence :

Il existe des start-ups ainsi que des entreprises historiques françaises spécialisées dans le même domaine qu’Ilek et/ou proposant des produits similaires en adoptant un mode de fonctionnement proche de l’entreprise toulousaine. +
_Exemple_ :

- _Ekwateur_ est un distributeur français indépendant d’énergies renouvelables proposant des énergies à base de gaz, de bois de chauffage ainsi que de l’électricité verte;
- _Hydronext_ est un fournisseur alternatif français et acheteur de productions électriques répartie sur plus de 300 sites en France;
- _Hydroption_ est un fournisseur toulonnais d’électricité verte produite en France dont la commercialisation se réalise auprès de consommateurs PME/PMI.

Mais aussi :

- _ENGIE_, troisième plus grand acteur et groupe industriel mondial de l’énergie;
- _EDF_, Premier producteur et fournisseur d’électricité et de gaz en France et en Europe.

=== Enjeux

Une entreprise ne se repose jamais sur ses acquis dû à l’évolution du marché et de ses probables concurrents. C’est une organisation en mouvement permanent qui s’adapte à l’environnement et aux nouveautés d’aujourd’hui. Ainsi, pour trouver des marchés inexplorés ou peu explorés, combler le plaisir des clients et apporter un service qualificatif dans les plus brefs délais, la structure saisit des opportunités qui lui sont offertes avec une présence continuelle de menaces diverses.

==== Enjeux politiques :

===== Opportunité(s) :

- Une partie des discussions réalisées par des politiciens s’orientent vers la décision que les objectifs des politiques des énergies renouvelables soient atteints.

===== Menace(s) :

- La rétraction des mesures politiques, autrement dit la réglementation, peut entièrement détruire le marché de l’énergie renouvelable.

==== Enjeux économiques :

===== Opportunité(s) :

La transition écologique est un secteur en progression pour lequel des opportunités d’emploi apparaissent fortement.

===== Menace(s) :

- Un risque de non-respect des ambitions et objectifs de l’entreprise éventuellement due à une faible clientèle;
- Les énergies renouvelables ne bénéficient pas à une économie en croissance dont les productions et les flux doivent être équilibrés et certains.

==== Enjeux socioculturels :

===== Opportunité(s) :

- Des ONG sur les enjeux de l’énergie, des personnalités fortes autour du climat comme Nicolas Hulot ou Greta Thunberg ou encore la crise du Covid-19 en 2020 ont amené à une prise de conscience importante sur la transition écologique.

===== Menace(s) :

Des menaces de manifestations, de grèves ou de mécontentement sont à envisager pour des arguments comme :

- Depuis une cinquantaine d’années, on évoquait le terme de “transition” sans aucun détonateur et dont la majorité des mesures étaient souvent reportées;
- La transition écologique ne se resserre pas uniquement à la transition énergétique puisqu’elle est également industrielle, écologique et surtout sociale.

==== Enjeux technologiques :

===== Opportunité(s) :

- Pour les producteurs locaux fiers de respecter l’environnement mais qui, pour certains, se sentaient délaissés et ne comptaient que sur leurs fidèles clients, Ilek a saisi l’opportunité d’une transition numérique afin de procéder à une visibilité plus raisonnable envers ces producteurs mais également de pouvoir exposer ses propositions des producteurs français. Enfin, cette transition numérique permet aux entreprises de faciliter la communication et de devenir plus compétitives.

===== Menace(s) :

- Toutefois, d’éventuels risques de sécurité au sein du site peuvent apparaître : il est nécessaire d’être en accord avec les enjeux de sécurisation en prenant en compte les contraintes d’architecture des banques de données.

==== Enjeux écologiques :

===== Opportunité(s) :

- La transition énergétique correspond à l’idée d’une diminution de la part d’énergies polluantes et d’une augmentation de celles du renouvelable.
- L’implantation de nouveaux projets renouvelables est la porte vers un nouveau modèle énergétique;
- L’ambition carbone car la mission ambitieuse de la structure est de diminuer l’empreinte carbone de tous les français avec un objectif de 1 milliard de kg de CO2 économisés.

===== Menace(s) :

- L’impact visuel sur le paysage généré par les barrages hydroélectriques pour la faune puisqu’ils peuvent inonder des vallées entières mais aussi les éoliennes augmentant la présence de lignes à haute tension. 
- La disposition des énergies renouvelables dépend du climat. Par exemple, lors de périodes anticycloniques, il n’y a pas de vent ; quand le ciel est nuageux, le rayonnement solaire est amoindri. Paradoxalement, Ilek dit “assurer” les fournitures d’énergie.

==== Enjeux légaux :

===== Opportunité(s) :

- Les énergies renouvelables devront représenter en 2030, -40% de la production d’électricité et -10% de la consommation de gaz d’après la loi. La société en a saisi l’opportunité de faire changer les choses progressivement et plus aisément.

===== Menace(s) :

- L’entreprise doit identifier les réglementations auxquelles elle est soumise telles que le partage et la confidentialité des  données des utilisateurs ainsi que les contraintes potentielles qu’elle peut générer et qui ne peuvent pas être respectées.
